version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "nuget"
    directory: "/site"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
